### ISSUE TITLE
Code block markers sometimes do not delimit a code block

### ISSUE THREAD

**Issue by nad** [agda/agda#2453]
Consider the following code:
```latex
\begin{code} text \end{code}
```
The literate Agda parser does not treat this as a code block, but the code is accepted. (And the LaTeX backend treats this as a code block: #2400.)

This can be confusing. I suggest that `\begin{code}` and `\end{code}` should be rejected unless they actually start or end a code block, or are commented out.

The current rule seems to be that `\begin{code}` must be at the end of a line (not counting whitespace), and that `\end{code}` must be at the beginning of a line (again, not counting whitespace). I'm fine with this rule.

**Comment by nad** [comment]
The LaTeX backend no longer treats
```latex
\begin{code} text \end{code}
```
as a code block. However, I still think that `\begin{code}` and `\end{code}` should be rejected unless they actually start or end a code block, or are commented out.

**Comment by nad** [comment]
Now the code above is rejected, but the following code is accepted: 
```latex
\end{code}

\begin{code} \end{code} \begin{co
F G : Set → {_ : Set} → Set
F = \begin{code} → begin
G = \end{code} → end
\end{code}
```
I'm not sure what to think of this code. I'm inclined to say that Agda should accept it. Any opinions?

**Comment by andreasabel** [comment]
1. I am surprised that `\end{code} \begin{co` are valid arguments to your code environment command.
2. Maybe `\begin` and `\end` should not be valid Agda identifiers.
3. Why is `\end{code}` by itself accepted?

**Comment by nad** [comment]
> 1. I am surprised that `\end{code} \begin{co` are valid arguments to your code environment command.

The code is not valid LaTeX, but it is valid literate Agda.

> 2. Maybe `\begin` and `\end` should not be valid Agda identifiers.

They are not, they are initial fragments of lambda abstractions. (I'm not very happy about the special case in the lexer for backslash followed by certain characters without intervening space, but for reasons of backwards compatibility I don't think we should change that part of the syntax now.)

> 3. Why is `\end{code}` by itself accepted?

To start with [Agda searches for](https://github.com/agda/agda/blob/ec2fe36f9ea8427aaac20c69e3ff2ded46f41f94/src/full/Agda/Syntax/Parser/Literate.hs#L158-L183) `\begin{code}` (not protected by percent characters), other code is ignored. This design (or accident?) can certainly be discussed. GHC does not accept the corresponding construction, but the Haskell 2010 report is [somewhat vague](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17900010.4) on whether or not it should be accepted.

**Comment by nad** [comment]
Currently `\%` is treated as a comment starter. I guess this should be fixed.

**Comment by jespercockx** [comment]
@nad do you think it is important to fix this before the next release?

**Comment by UlfNorell** [comment]
I don't see any serious problem remaining. Dropping the milestone.

**Comment by nad** [comment]
One remaining issue is that the LaTeX backend treats `\%` as a comment starter. However, as far as I understand one can dynamically change the comment characters in LaTeX, so I think we can keep the current implementation. This would mean that, as far as Agda is concerned, `%` is always a comment character (and no other character is). Perhaps this should be documented somewhere.

Another remaining issue is that Agda accepts arbitrary uses of `\end{code}` before the first `\begin{code}`. I think it makes sense to follow GHC and reject that kind of code.

**Comment by nad** [comment]
I have tried to document the current behaviour:

> Agda finds code blocks by looking for the first instance of `\begin{code}` that is not preceded on the same line by `%` or `\` (not counting `\` followed by any code point), then (starting on the next line) the first instance of `\end{code}` that is preceded by nothing but spaces or tab characters (`\t`), and so on (always starting on the next line). Note that Agda does not try to figure out if, say, the LaTeX code changes the category code of `%`.

Perhaps it would make sense to change the semantics as outlined [above](https://github.com/agda/agda/issues/2453#issuecomment-388412965), or in order to simplify the quoted text.
