### ISSUE TITLE
Turn unsolved instance error into a warning

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2514]
Unsolved metas should give a warning instead of an error.  Instance and unification metas should be handled in the same way.

See also #2172.

**Comment by gallais** [comment]
What about `InstanceSearchDepthExhausted`? Should it also be a warning?

**Comment by andreasabel** [comment]
I think whenever no solution is found, it should be like an unsolved meta.  If two or more solutions are found, it can be an error (as this does not go away by more information, does it?).

**Comment by gallais** [comment]
Ok it's a hard one. This [typeError](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L228) seems to be an integral part of the control flow of the search. If it is turned into a warning, some files (such as `test/Succeed/Issue1532.agda`) do not check anymore.

[This auxiliary function](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/InstanceArguments.hs#L543) seems to be the culprit: when an exception is raised, it captures it and returns `No`. When we move to warnings, we get a `Yes` or a `Maybe` instead.

I can't see any code re-throwing the exception but that doesn't mean that throwing a dummy one solves the problem: it does manage to reach the toplevel somehow. ~~Given that a test on `test/Fail/InstanceArgumentsNotFound.agda` collects *two* warnings for a single unresolved instance,~~ I guess this part of the code is reached from two different points.

**Comment by andreasabel** [comment]
Naive suggestion: catch the `IFSNoCandidateInScope` on the top level and turn it into a warning.  Top level means outside of the recursive instance search.

**Comment by UlfNorell** [comment]
> I think whenever no solution is found, it should be like an unsolved meta. If two or more solutions are found, it can be an error (as this does not go away by more information, does it?).

FYI, it's only an error if instance search fails irretrievably, i.e. there's no more information that could appear to make an instance be found.

**Comment by UlfNorell** [comment]
In fact, once the problem with errors being integral to instance search (and also reflection with `catchTC`) is solved, it might make sense to turn *all* type errors into warnings in order to get all errors in one go instead of just the first one.

If checking a term fails we can simply create a place-holder meta and keep going.

**Comment by gallais** [comment]
> If checking a term fails we can simply create a place-holder meta and keep going.

Surely we would have to prevent this meta from being solved by unification?

**Comment by UlfNorell** [comment]
We certainly could, but I don't think we have to. We'll still get the error and it might be that further errors are more informative if we allow the place holder to be instantiated with the "correct" value.

**Comment by UlfNorell** [comment]
Experimenting with errors as warnings on [a branch on my fork](/UlfNorell/agda/tree/issue2514). There are some interaction test issues I haven't looked into and some of the changed errors from test/Fail in https://github.com/UlfNorell/agda/commit/17fa35bb6abb1c0bfe63beb4b04acef8fa08f264 are not clearly correct.

**Comment by nad** [comment]
What about performance? Unsolved metas can slow Agda down. Are the warnings presented when they are encountered, or all at the same time?

**Comment by nad** [comment]
As discussed [elsewhere](https://github.com/agda/agda/issues/5279#issuecomment-813984791) it might be easier to identify the cause of a performance regression in existing code if Agda warned about unsolved meta-variables as soon as possible. How hard would this be to implement?

**Comment by nad** [comment]
> As discussed [elsewhere](https://github.com/agda/agda/issues/5279#issuecomment-813984791) it might be easier to identify the cause of a performance regression in existing code if Agda warned about unsolved meta-variables as soon as possible.

Ideally this should be done also for imported modules, not only the top-level one.

**Comment by andreasabel** [comment]
I think it is better to open a new issue for your request, @nad.  This only has vaguely to do with the OP.
