### ISSUE TITLE
Make more primitive/builtin modules safe?

### ISSUE THREAD

**Issue by nad** [agda/agda#2783]
Currently quite a few `Agda.Builtin` modules cannot be type-checked in `--safe` mode. In the case of `Agda.Builtin.TrustMe` this is good, but perhaps it should be possible to type-check `Agda.Builtin.Char`, `Agda.Builtin.Float`, `Agda.Builtin.IO` and `Agda.Builtin.String` in this mode.

I'm not sure what the `--safe` status of `Agda.Builtin.Reflection` should be. I would hope that all constructions in this module are safe.

I'm also not sure what the `--safe` status of `Agda.Primitive` with the new cubical primitives should be.

**Comment by nad** [comment]
See also #2784.

**Comment by adlerd** [comment]
It looks like a lot of things may have been cleaned up, but there's a hidden gotcha with Agda.Builtin.Reflection. It checks with --safe, but `Term` equality isn't decidable because the primitives for `Meta` and `QName` equality are `... -> Bool`. This makes it pretty difficult to use reflection; although in `TC` I guess `unify` is kind of like equality checking...

**Comment by MatthewDaggitt** [comment]
Mostly fixed by @gallais in e134cce

**Comment by jespercockx** [comment]
Since https://github.com/agda/agda-stdlib/issues/143 is closed, can we now close this issue as well?

**Comment by gallais** [comment]
We are still missing `Agda.Builtin.IO` from @nad's original issue. Although we could
make it safe (the type is trivially inhabited by `Identity`), I have no intention of working
on it:

* the IO in the stdlib uses `NON_TERMINATING`
* the library of sized IO I'm working on uses `NO_UNIVERSE_CHECK`.

**Comment by nad** [comment]
It might make sense to turn on `--safe` in more builtin modules:

* Everything related to `--cubical`. @Saizan, is there a reason not to do this?

* My guess is that it is OK to mark `Agda.Builtin.Reflection` as safe, because the `TC` definitions do not compute (unless they are used by macros), and all definitions can be implemented if `TC` is instantiated to `λ _ → ⊤`.

* Similarly, it seems to me as if `Agda.Builtin.IO` could be marked as safe.

A very simple way to achieve this would be to turn off safety checking in these modules.

**Comment by fredrikNordvallForsberg** [comment]
I removed the need for postulates in ``Agda.Builtin.IO`` and ``Agda.Builtin.Reflection``. This only leaves ``Agda.Builtin.Cubical.*`` (waiting for @Saizan's confirmation that these are safe).

**Comment by nad** [comment]
The user manual should also be updated (at least `built-ins.lagda.rst` and `reflection.lagda.rst`).

**Comment by Saizan** [comment]
```Agda.Builtin.Cubical.*``` does not introduce any unsafe primitives or so.

**Comment by fredrikNordvallForsberg** [comment]
@jespercockx said elsewhere:
> I don't think this is a good idea, now you cannot see the type of the builtins anymore in the place where it is defined (or rather, there is no more definition). I think it would be better to leave them as postulates and add a special rule that postulates in builtin files are fine even with --safe.

Nothing stops users from editing the installed builtin files though, so this would be a way to work around `--safe`... But actually this is already a problem with `Agda.Primitive`, so maybe this shouldn't hold us back.

@gallais said:
> Alternatively: we could make them primitives.

This would mean that the user cannot choose the name, but perhaps that would be okay...

Finally, a third solution would be to make `--safe` accept postulates ending in `Set` and in postulated types (since these can be implemented by the unit type). The compiler could then actually translate them to the unit type (to avoid safe, crashing programs).

**Comment by nad** [comment]
> Nothing stops users from editing the installed builtin files though, so this would be a way to work around `--safe`...

If an adversary can edit those files on your machine, then it is not inconceivable that this adversary can also install a patched version of Agda.
