### ISSUE TITLE
Allow metaprogramming to generate top level definitions other than functions

### ISSUE THREAD

**Issue by dylanede** [agda/agda#3699]
Currently (I believe) metaprogramming is only capable of generating function declarations and definitions at the top level. It is not capable of defining data types or instantiating other constructs like `open`. Adding these other capabilities would really help with reducing repetitive code.

**Comment by jespercockx** [comment]
This has been on my todo list for a long time, but I'm not sure if I will ever find the time for it. IIRC the main problem is the scope checker, which needs to know the names of all the constructors but runs *before* any reflection code.

**Comment by JacquesCarette** [comment]
So some of the things that @alhassy is working on will very much need this. He's currently hacking it (by doing it externally to Agda). It is high enough on his priority list that he might well be the labour that gets this done - if he gets the right guidance as to how to do it 'right'. So documenting what you'd do (to the scope checker) to resolve this impasse would not be a waste of your time.

**Comment by jespercockx** [comment]
I guess the main problem here is that it would require an architectural change of the typechecker, which is currently split up strictly in two phases: first scope checking, then type checking. What we would need instead is that we check declarations one by one (or mutual block by mutual block), doing both scope checking and type checking for each one. Then the typechecker would be able to send information back to the scope checker (e.g. introduce a new name) that it could take into account while checking the *next* block.

I'm tagging @UlfNorell here because he probably knows the overall architecture better than I do.

**Comment by xekoukou** [comment]
The type of architecture is pretty crucial for many other things, ex. parallelization and use of agda as a server etc.

**Comment by UlfNorell** [comment]
The alternative to messing with scope checking is to not bring generated constructors into scope and use some other mechanism to refer to them. Maybe some combination of hint databases and pattern macros.

**Comment by alhassy** [comment]
@jespercockx I'm happy to undertake this task, though I will need some guidance.

**Comment by jespercockx** [comment]
@alhassy That's great to hear! Just let me know when you need to know anything and I'll do my best to help.

**Comment by uhbif19** [comment]
Was not this issue solved by PR above?

**Comment by L-TChen** [comment]
IIUC, record types are still not definable by metaprogramming.
