### ISSUE TITLE
Support cabal-install 3.0.0.0 in the Makefile

### ISSUE THREAD

**Issue by asr** [agda/agda#4216]
I created this issue for collecting/reporting the required changes/issues for supporting `cabal-install 3.0.0.0`.

**Comment by UlfNorell** [comment]
We already made the necessary changes as part of the `ghc-8.8` support (#3725) unless I'm very much mistaken. At least I've been using `cabal-3.0.0.0` without issue since then. Is the `ghc-8.8` Travis job not using `3.0.0.0`?

**Comment by asr** [comment]
The Travis job for GHC 8.8.1 is using `caba-install 2.4.1.0`.

**Comment by asr** [comment]
I got an error when running `cabal install` in a fresh repository. I'll report the error later.

**Comment by L-TChen** [comment]
`cabal-3.0` works well to me. 

The following one is built with GHC 8.8.1 and cabal 3.0 

https://travis-ci.org/L-TChen/agda/jobs/614341754

**Comment by asr** [comment]
The above job don't use `cabal-install` but `stack`.

**Comment by UlfNorell** [comment]
> I got an error when running cabal install in a fresh repository.

You have to use `cabal v1-install`.

**Comment by L-TChen** [comment]
```
Stack has not been tested with GHC versions above 8.6, and using 8.8.1, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.0.0 was found, this may fail
```
If I was not mistaken, stack uses cabal to install packages ... 
https://docs.haskellstack.org/en/stable/faq/#what-is-the-relationship-between-stack-and-cabal

**Comment by asr** [comment]
I think `stack` uses `Cabal` the library, but it doesn't use `cabal-install` the program.

**Comment by asr** [comment]
> You have to use `cabal v1-install`.

I guess. Are you planning to update the [user documentation](https://agda.readthedocs.io/en/latest/getting-started/installation.html#installation-from-hackage) for taking care of the different versions of `cabal-install`?

**Comment by asr** [comment]
Running `cabal-install` the first error I got is

```bash
$ cabal install
cabal: filepath wildcard 'doc/user-manual.pdf' does not match any files.
```

This is also the error in Travis when using GHC 8.8.1 and `cabal-install 3.0.0.0`.

**Comment by nad** [comment]
I think the idea is to eventually deprecate `v1-install`, so I guess we should at some point make `v2-install` work.

**Comment by ice1000** [comment]
I'm building Agda with cabal 3.0.0.0 for weeks. It always work

**Comment by L-TChen** [comment]
> I'm building Agda with cabal 3.0.0.0 for weeks. It always work

Can you make a GH Actions workflow using cabal 3.0 with v2-install? Just make sure that Agda is compatible.

**Comment by ice1000** [comment]
How did you make the stack one? Is it just porting the `.travis.yml`?

**Comment by L-TChen** [comment]
Almost. GHC, cabal (2.0-3.0) and stack are all preinstalled already, so it should be simpler. 

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

**Comment by nad** [comment]
> I'm building Agda with cabal 3.0.0.0 for weeks. It always work

Then perhaps the makefile could be updated to use `install` instead of `v1-install`. (Just dropping the `v1-` prefix does not work.)

**Comment by L-TChen** [comment]
It seems that by removing `doc/user-manual.pdf` from `extra-source-files` in `Agda.cabal`, it actually compiles https://github.com/agda/agda/commit/e956e9d356750c0fe92477c3ecbca70edaf56f2b/checks?check_suite_id=328447539

I haven't run the test suites with the compiled binary, though. Adding this workflow might be a good idea before revising Makefile? I am not able to revise Makefile this year anyway ...

**Comment by asr** [comment]
> It seems that by removing `doc/user-manual.pdf` from `extra-source-files` in `Agda.cabal`, it actually compiles.

Yes. Please remove it. I'll add it back in the releases branches.

**Comment by asr** [comment]
The issue is fixed for the final user which was my goal and the CI is using `cabal 3.0.0.0` (thanks @L-TChen) .

@L-TChen wrote:
> I am not able to revise Makefile this year anyway

I'm not planning to revise the Makefile. So, I renamed the issue, bumped its milestone and assigned it to @L-TChen.

**Comment by L-TChen** [comment]
It turns out that it is not so simple to support the new nix-style build system.
Oddly, `cabal new-install --enable-tests` emits the error message (bug?)
```
cabal: --enable-tests was specified, but tests can't be enabled in a remote package
```
I tried using `cabal new-configure` instead. However `cabal new-configure` does not seem to use `--builddir`, as `cabal new-build` always build inside `dist-newstyle` instead of `dist-2.6.1` as specified.

It looks like a bug of cabal. Any workaround?

**Comment by asr** [comment]
Maybe the section "cabal install ≠ Setup install" from [The Cabal of Cabal](http://www.vex.net/~trebla/haskell/cabal-cabal.xhtml) explains the problem and shows the solution:

\begin{quote}

Many people use this idiom in a source tree to build and install:

```
cabal configure
cabal build
cabal install
```

This idiom is an urban legend, i.e., a popular error. The 3rd step cabal install re-does the 1st and 2nd steps, among other things. Redundant work looks harmless so far, until one day you need non-default options:

```
cabal configure --prefix=/nondefault --flags=debug
cabal build
cabal install
```

Whee! Your laborously entered options are lost on deaf ears. The 3rd step cabal install without options re-does cabal configure without options. Your options are erased.

The correct idiom is:

```
cabal configure --prefix=/nondefault --flags=debug
cabal build
[cabal haddock [--hyperlink-source]]
cabal copy
cabal register
```

\end{quote}

**Comment by L-TChen** [comment]
As far as I remember, it was the step `cabal new-build` which failed to build in the specified directory instead of `cabal new-install`. I will check it again later anyway.

**Comment by L-TChen** [comment]
I now see why it does not work. In the [document](https://cabal.readthedocs.io/en/latest/nix-local-build.html#cmdoption-builddir), it says 

> This option (--builddir) cannot be specified via a cabal.project file.

so even if it is specified by `cabal configure --builddir=DIR` it simply results a `cabal.project` which `cabal build` reads later on. That's the reason why `cabal configure --builddir=DIR` does not work. 

I will try to finish this issue during this week.

**Comment by nad** [comment]
One issue with Nix-style builds is that the `agda` binary is stored in a [new location](https://www.haskell.org/cabal/users-guide/nix-local-build.html#where-are-my-build-products), which varies depending on things like the OS and the version of GHC. Our test suite (mostly?) uses this binary, rather than the binary from the PATH. Perhaps we could use something like `cabal v2-run` instead.

**Comment by nad** [comment]
I have read up on and tested some of the `v2-` commands. The new Nix-style builds are sort of like Cabal sandboxes with a global cache. This sounds good, and I'd like to switch.

I noticed that `cabal v2-install` rebuilds the package from scratch if it isn't built already. However, `cabal v2-build` seems to reuse earlier results.

I suggest that, for simplicity, we drop support for older versions of Cabal/cabal-install, and only support the `v2-` commands in the Makefile. (For forwards compatibility the prefixes should be included.) GHC 8.0.2 requires the use of Cabal/cabal-install 1.24 or later, and this version of cabal-install does not support the `v2-` commands. However, building cabal-install 3.0.0.0 using GHC 8.0.2 and cabal-install 1.24.0.2 worked when I tried it. (A caveat: Some of the dependencies had already been built.) Does this sound OK? How common is it that users install Agda using `make install` rather than `cabal install Agda`?

**Comment by nad** [comment]
> Perhaps we could use something like `cabal v2-run` instead.

That seems to make `agda --help` quite a bit slower (more than 0.1 s on my machine), and the test suite invokes Agda many times. A better idea may be to run the test-suite inside a new shell started using (say) `cabal v2-exec sh`, in which case `agda` points to the newly built program.

**Comment by nad** [comment]
> I noticed that `cabal v2-install` rebuilds the package from scratch if it isn't built already. However, `cabal v2-build` seems to reuse earlier results.

Unfortunately it seems as if `v2-install` starts the build from scratch, even if you run it right after `v2-build` has completed. Does anyone know a workaround for this? Is there a different, convenient way to install things?

**Comment by nad** [comment]
One possible drawback of `v2-install` is that all data files (like the Emacs mode) are installed in the Cabal tree (in my case under `~/.cabal/`), and as far as I can tell there is no way to specify that they should be installed somewhere else. This means that the path to the Cabal tree is baked in to the executables (`agda` and `agda-mode`). If you want to place the data files somewhere else (like under `/usr/share/agda`), then you can work around this by setting the environment variable `Agda_datadir` in a wrapper script, but this is a little more inconvenient.

**Comment by nad** [comment]
It seems as if we can build Agda without optimisations, in a separate build directory, by running `cabal v2-build --project-file=Agda-quick.project --builddir=dist-quick -fenable-cluster-counting`, where `Agda-quick.project` contains the following text:
```
packages: Agda.cabal

package Agda
  optimization: False
  program-suffix: -quick
```
One can add local settings in a file called `Agda-quick.project.local`.

As an alternative one can skip the project file: `cabal v2-build --builddir=dist-quick -fenable-cluster-counting --disable-optimisation --program-suffix=-quick`.

**Comment by nad** [comment]
It seems as if Cabal 3 uses separate build directories automatically, one component of the build path is called `noopt`:
```
[369 of 369] Compiling Agda.Main        ( src/full/Agda/Main.hs, […]/dist-quick/build/i386-linux/ghc-8.8.3/Agda-2.6.1/noopt/build/Agda/Main.o ) [flags changed]
```
Thus we could perhaps skip `--builddir`.

**Comment by nad** [comment]
> Unfortunately it seems as if `v2-install` starts the build from scratch, even if you run it right after `v2-build` has completed. Does anyone know a workaround for this?

I guess having separate Cabal files for the library and the executables would help. A related issue: #4359.

However, the obvious way to do this would presumably entail uploading at least one extra package to Hackage, like we [used to do](https://hackage.haskell.org/package/Agda-executable). Do we want to pollute Hackage with a package that may not have independent interest? Note that the library Agda is not designed to be used by others, and that we do not follow the package versioning policy for it.

An alternative would be to use multiple packages for development and to merge them before the release, but that sounds awkward.

**Comment by nad** [comment]
> I guess having separate Cabal files for the library and the executables would help.

But it seems as if I was incorrect, when I put the library and agda-mode in different Cabal files, added a `cabal.project` file, and asked cabal-install to install agda-mode, cabal-install started building the library in a temporary build tree.

**Comment by asr** [comment]
> Note that the library Agda is not designed to be used by others

But it doesn't prevent that others use [Agda as a library](http://packdeps.haskellers.com/reverse/Agda).

**Comment by L-TChen** [comment]
It looks like there is a proper way to include sub-libraries in one cabal package: 

https://fgaz.me/posts/2019-11-14-cabal-multiple-libraries/

which requires cabal 3.0, though. [ I'd like to suggest developers to update their system to at least nix-style cabal and compatible ghc versions, the toolchain is much better. ]

**Comment by nad** [comment]
> `cabal v2-build --project-file=Agda-quick.project --builddir=dist-quick -fenable-cluster-counting`

Unless I'm mistaken the flag `-fenable-cluster-counting` applies to all packages that are built. It might be better to put it in a `.project` file, then one can specify that it only applies to the package Agda. However, I don't want it to be enabled by default for regular users, only for CI and for people who develop Agda. Perhaps we could put the flag in a `.project` file and remove it when releasing Agda.

> `cabal v2-build --builddir=dist-quick -fenable-cluster-counting --disable-optimisation --program-suffix=-quick`

Similarly I guess that `--disable-optimisation` should not be on the command-line.

**Comment by nad** [comment]
> which requires cabal 3.0, though.

And GHC 8.8.

> [ I'd like to suggest developers to update their system to at least nix-style cabal and compatible ghc versions, the toolchain is much better. ]

If that is the case, can you explain to me how I can install Agda without rebuilding everything from scratch?

**Comment by nad** [comment]
Another problem with `v2-install`: If the build crashes (if it runs out of memory, or if GHC panics), then you have to start from scratch.

**Comment by L-TChen** [comment]
> If that is the case, can you explain to me how I can install Agda without rebuilding everything from scratch?

Interesting. I thought the new build system actually wants you to separate local builds from global builds as the [document](https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html) says 

> Like non-sandboxed Cabal today, builds of external packages are cached in ~/.cabal/store, so that a package can be built once, and then reused anywhere else it is also used. No need to continually rebuild dependencies whenever you make a new sandbox: dependencies which can be shared, are shared. 

So, yes, if you want to install Agda globally to the system, everything will be built again from scratch.  However, it is always possible to run Agda inside the sandbox. So, the goal should be having an option to change the location of compiled binary in Emacs easily. For end users, they normally install it by `cabal install` or from the existing package manager, I assume? 

[ sorry, the original comment was for another issue, but I overlooked. ]

**Comment by L-TChen** [comment]
> Does this sound OK? How common is it that users install Agda using make install rather than cabal install Agda?

Well, the order of installation/compilation methods on macOS for me is 

1. Homebrew
2. Prebuilt binary from the official website
3. Whatever indicated by the official instruction. Usually, it is `git clone [repo]` followed by `cabal install` or `stack install`. I don't install executables directly from `cabal` as it rarely works.  
4. try `make` or `make help` to see if there is anything available. As for Agda, I felt annoyed when the target `help` did not exist (so I wrote one). 


For working on a package, the order is reversed.

**Comment by nad** [comment]
> However, it is always possible to run Agda inside the sandbox.

Note that the binaries include paths to data files that may not have been installed yet:
```
$ cabal v2-exec agda-mode locate; echo
[…]/.cabal/share/i386-linux-ghc-8.8.3/Agda-2.6.1/emacs-mode/agda2.el
```
One can work around this by setting the `Agda_datadir` environment variable. This seems to be taken care of by `v2-run`:
```
$ cabal v2-run -v0 agda-mode locate; echo
[…]/./src/data/emacs-mode/agda2.el
```
However, as noted above `v2-run` comes with a substantial overhead (when used thousands of times).

> So, the goal should be having an option to change the location of compiled binary in Emacs easily. 

I don't want to complicate the Emacs mode due to problems with the build system.

> For end users, they normally install it by `cabal install` or from the existing package manager, I assume?

There may be some "end users" who use the development version and recompile frequently. I don't want to increase build times substantially for this group.

A workaround might be to ditch `v2-install` in the makefile, and to install the binaries and the data files manually. (One remaining drawback is that the library would still be rebuilt if it is needed by some other development.)

However, we are not forced to switch to the `v2-` commands before the `v1-` commands are removed from `cabal`. (When Cabal 4 is released?) Another option is to ask whether `cabal` could be changed. I'm guessing that things are rebuilt from scratch to make things more robust. However, one could presumably add a flag to `v2-install` that instructs it to reuse the `v2-build` build directory, with a caveat that things might be less robust if this flag is used.

**Comment by L-TChen** [comment]
> However, we are not forced to switch to the v2- commands before the v1- commands are removed from cabal.

That's true. Adopting to `v2-` commands completely requires a number of breaking changes including ditching older ghc versions (@jespercockx has downvoted this change), and it should be made under the consensus among active developers. There are pros such as reducing some conditional compilation in the codebase, simplifying the configuration and maintenance, etc. as well as cons you mentioned. 

I moved this issue to icebox as I find it hard to have a conclusion unless above problems are sorted.

> However, as noted above v2-run comes with a substantial overhead (when used thousands of times).

> Another option is to ask whether cabal could be changed.

Maybe we can move on by asking if the `cabal` development team can resolve these issues first.

**Comment by nad** [comment]
I don't think we need to drop support for older versions of GHC, Cabal 3 is supported by GHC 8.0, and even if we change the makefile people can still use older versions of Cabal to install Agda.

**Comment by L-TChen** [comment]
> even if we change the makefile people can still use older versions of Cabal to install Agda

Does that mean it is safe to use nix-style local build only in the `Makefile`? It is rather tricky to maintain two different sets of commands as their options do not correspond to each other nicely in our setting as far as I remember.

**Comment by asr** [comment]
Usually there is one version of `cabal-install` associated to a version of GHC via its shipped libraries. We need to test the build of Agda using these versions of `cabal-install`.

**Comment by nad** [comment]
> Does that mean it is safe to use nix-style local build only in the `Makefile`?

I'm not sure what you mean. I think we should stick to either `v1-` or `v2-` in the makefile, and as discussed above there are some problems with `v2-`.

**Comment by L-TChen** [comment]
> I'm not sure what you mean. I think we should stick to either `v1-` or `v2-` in the makefile, and as discussed above there are some problems with `v2-`.

I am just trying to figure out the current consensus 

1.  `Makefile` should either use `v1-` or `v2-` commands;
2. the above issues should be resolved before moving to the `v2-` commands;
3. cabal 3 is supported by GHC 8.0+, so adopting `v2-` commands does not need to drop older GHC versions;
4. however, there is one cabal version associated to a GHC version, and every supported version should be tested. 

So, it implies that 

1. unless issues with cabal 3 are solved, `Makefile` should not be changed; 
2. if `Makefile` is changed to the `v2-` style we still need to test the `v1-` style somewhere like the GitHub workflow script `cabal build`.

Is that correct?

**Comment by nad** [comment]
I think this sounds more or less correct.

**Comment by asr** [comment]
What about to use two Makefiles (something like `Makefile` and `Makefile-new-cabal`). We could use both Makefiles in Travis and GitHub. Every developer could use the more appropriate `Makefile` for his set up. Eventually `Makefile` will be obsolete and then we will rename `Makefile-new-cabal` to `Makefile`?

**Comment by nad** [comment]
I don't think we should make things more complicated. I suggest that we switch to the new Cabal commands when or if the problems identified above have been addressed in some suitable way.

**Comment by asr** [comment]
Even if the problems you mentioned were fixed, the CI uses the `Makefile` and we need to test the versions of `cabal-install` for "default" for each GHC supported version.

**Comment by andreasabel** [comment]
To migrate to v2-cabal these problems remain for me:
- [ ] `make type-check`:  The v1-solution passing `--ghc-options=-fno-code` does not work with v2-cabal, as it wants then to reinstall all the dependencies (haskell/cabal#1176, haskell/cabal#7368)
- [ ] `make install-bin`: `cabal install` after `cabal build` recompiles Agda from scratch, since it compiles from the `sdist`-tarball.  One could try to work around this by writing a script that copies the relevant bits from the build tree to the `--installdir`. (https://github.com/haskell/cabal/issues/6919#issuecomment-784559678)

**Comment by mouse07410** [comment]
Could you clarify the status of this issue/effort? How long till there's a version of `Makefile` (or of `mk/cabal.mk`) that uses `v2-` commands?

If one doesn't want to mess with his Haskell environment using `cabal v1-` commands, how can one build **and install** the current (master) Agda from the source (cloning this repo), if one wants to also run tests?

Should the following work (in sequence as typed):
- `cabal build | tee >(copy-bins.awk)`
- `make bugs`
- `make test`
?

**Comment by andreasabel** [comment]
My latest efforts are at: https://github.com/agda/agda/blob/7f58030124fa99dfbf8db376659416f3ad8384de/src/github/workflows/cabal-test.yml#L93-L110

**Comment by nad** [comment]
> * `cabal build | tee >(copy-bins.awk)`

If you have a recent version of cabal-install, then you can perhaps use `cabal list-bin` to find the path to the executable.

**Comment by mouse07410** [comment]
```sh
$ cabal list-bin agda
cabal: No or multiple targets given

$ cabal list-bin agda-tests
cabal: No or multiple targets given

$ cabal list-bin agda-mode
cabal: No or multiple targets given

$ cabal list-bin
cabal: One target is required, none provided

$ cabal list-bin --project-file=Agda.cabal agda
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.

$ cabal list-bin --project-file=Agda.cabal agda-mode
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.

```

**Comment by mouse07410** [comment]
Also, please take a look at https://github.com/haskell/cabal/issues/7693 - perhaps it would be helpful here, or you might be able to give some useful feedback there.

**Comment by fgaz** [comment]
https://github.com/agda/agda/issues/4216#issuecomment-930142519 looks like haskell/cabal#7679

**Comment by mouse07410** [comment]
> #4216 (comment) looks like haskell/cabal#7679

They are two different aspects of the same problem:

- https://github.com/haskell/cabal/issues/7679 is about how to make Cabal build and install dependencies even when `--enable-tests` is set.
- https://github.com/agda/agda/issues/4216#issuecomment-930142519 is about how to modify Agda installation and testing process to avoid triggering the problem that Cabal introduces for `v2-` commands.

**Comment by mouse07410** [comment]
As asked [here](https://github.com/haskell/cabal/issues/7693#issuecomment-930388089) - what's the point of having `--only-dependencies` in the install command? Since we install the generated binaries before running tests anyway - why not ditch that parameter altogether???

**Comment by andreasabel** [comment]
> As asked [here](https://github.com/haskell/cabal/issues/7693#issuecomment-930388089) - what's the point of having `--only-dependencies` in the install command? Since we install the generated binaries before running tests anyway - why not ditch that parameter altogether???

Dunno, maybe @asr can say more.

I can see a use for `--only-dependencies` in the following cases:
- CI: First install dependencies, cache them for the next time, then install Agda but don't cache it.  (This is what is often done in the github workflows.)
- Developer: Install dependencies with optimization on, but build Agda without optimizations for quick testing.  (This at least made sense with v1-cabal, the situation with v2-cabal is more confusing.)

**Comment by mouse07410** [comment]
1. CI: I don't think dependencies that did not change themselves, would be rebuilt - therefore, no need to worry about them.
2. Developer: I understand the logic, but I'm pretty sure that (unlike in C/C++) you cannot build dependencies with one set of flags, and then build the "main" package with another set of flags _without having all the dependencies **rebuilt**_. Difference in the flag set can be minimal - one flag would be sufficient to force the rebuild/recompile.

**Comment by L-TChen** [comment]
> * CI: First install dependencies, cache them for the next time, then install Agda but don't cache it. (This is what is often done in the github workflows.)

As for CI, the main benefit of using `--only-dependencies`, I think, is to navigate the error information easier.

**Comment by mouse07410** [comment]
OK, so having had all this discussion and observing what Cabal maintainers got to say about this, where are we regarding move to `cabal v2-` build? 

### Update

It looks like the sequence for `cabal v2-...` should be
1. `cabal v2-build --enable-tests --only-dependencies` (optional, I don't fully understand what separating this step accomplishes, given that CI probably builds everything)
2. `cabal v2-build --enable-tests`
3. actually running tests - and here's my stumbling block: how do I get all the Agda tests to run, given that I know where `agda`, `agda-mode`, and `agda-tests` binaries are?
4. finally, `cabal v2-install` that will place the Agda binaries into the global store `~/.cabal/bin` and `~/.cabal/store`

Do you concur? If so, how to deal with (3) above?

### Update 2
Specifically, what scripts and `mk/*.mk` files do I need to modify, to get `make test` working with this new build? Assuming that I know the locations of `agda`, `agda-mode`, and `agda-tests`?

**Comment by jespercockx** [comment]
This issue has been dormant for a while now, but it is still desirable to move to the 'new' cabal commands eventually (and preferably soon). I must say I don't quite understand all the subtleties in the discussion above, but perhaps the issues that once existed in Cabal have been resolved, or at least there might be workarounds that are good enough.

@andreasabel

**Comment by jespercockx** [comment]
@asr suggested the following alternative to `cabal install` earlier in this issue:

```
cabal configure --prefix=/nondefault --flags=debug
cabal build
[cabal haddock [--hyperlink-source]]
cabal copy
cabal register
```

Perhaps we could update `make install` to use this sequence instead?

Update: `cabal copy` does not seem to be a known command for my installed version of cabal (3.14.1.1).
